version: '3.8'

services:
  # PostgreSQL with PostGIS and pgvector extensions
  postgres:
    image: postgis/postgis:16-3.4
    container_name: discover_postgres
    environment:
      POSTGRES_USER: discover_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: discover_property
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    command: >
      postgres
      -c shared_preload_libraries=postgis
      -c log_statement=all
      -c log_destination=stderr
      -c logging_collector=on
      -c log_directory=/var/log/postgresql
      -c log_filename=postgresql.log
    networks:
      - discover_network

  # Elasticsearch for search functionality
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: discover_elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=discover-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - discover_network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: discover_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - discover_network

  # Kibana for Elasticsearch management (optional)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: discover_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - discover_network

volumes:
  postgres_data:
  elasticsearch_data:
  redis_data:

networks:
  discover_network:
    driver: bridge